from . import (person_mixin,
               doctor,
               contact_person,
               personal_doctor_history,
               patient,
               patient_test,
               disease_type,
               sample_type,
               test_type,
               disease,
               diagnosis,
               visit,
               )
